### ISSUE TITLE
project support

### ISSUE THREAD

**Issue by bestw** [matthewferreira/cppcheck-extension#13]
The ext is very excellent, and can you support cppcheck --project=cmake/vs? It is very useful when we use cmake/vs... Thank you very much.

**Comment by matthewferreira** [comment]
This is now covered with the 'projectFile' configuration option. The analyzer will expand environment variables and ${workspaceRoot} when trying to use the provided option.

**Comment by matthewferreira** [comment]
I have not heard from you in a while. I am closing this feature request. If it does not work, please reopen.
