### ISSUE TITLE
Allow c++14 as valid standard

### ISSUE THREAD

**Issue by sjiekak** [matthewferreira/cppcheck-extension#16]
Currently C++14 is a valid standard in cppcheck but not in the plugin. 
Can you add it ?

Also, why is the plugin doing it's own check for these types of parameters? It forces the plugin to "keep up" with cppcheck changes, while it could be possible to pass the parameter to the underlying cppcheck executable and forward any occurring errors.

**Comment by matthewferreira** [comment]
C++14 should now be the default in version 0.2.2. As for passing arbitrary parameters to the underlying engine, that could be a separate feature request. The extension checks most options otherwise in order to give a better user experience ("it just works").
