### ISSUE TITLE
Error Highlighting

### ISSUE THREAD

**Issue by apazureck** [matthewferreira/cppcheck-extension#2]
Hi @matthewferreira,

Thanks for that great extension. Worked really well so far.

Would you welcome contribution? I would like to integrate a diagnostics provider, which will highlight lines with errors from the compiler and your cpp check. Or have you done sth. like that and did not sync it here?

Cheers

**Comment by matthewferreira** [comment]
Contributions would be fine with me. I haven't had any further plans with this extension. Were you thinking of parsing the output of cppcheck and any compiler directly? Interacting with a compiler sounds like it would be a separate extension.

**Comment by apazureck** [comment]
Have a look at my fork. I used the cppc output to show it directly in written code.

![grafik](https://cloud.githubusercontent.com/assets/14858596/24374520/7813e33c-1335-11e7-8b0f-469bcafe24ae.png)

I also added the option to run the compiler on save in background to get an additional error if it did not run well. This is for mingw only, as I am using it for now. And it is for simple compiling one file and nothing like cmake or bigger projects for now, but a start at least.

It is pre-release. I would like to extend it to get the user to add additional compiling options (or override the defaults) to give the needed flexibility.

I don't want to create a new extension doing more or less the same stuff you do just with some fancy underlining. The marketplace is full of (sadly often useless) stuff and so I would like to extend and promote good extensions like yours.

**Comment by matthewferreira** [comment]
I wasn't saying not to improve my extension. What I meant was that I had nothing in mind to do feature-wise. I think underlining at least the cppcheck output is a great improvement. For compiler parsing I was thinking perhaps something like a plugin system for each supported compiler. You have mingw done, VC++ would be an obvious target, along with clang.

**Comment by apazureck** [comment]
Great to hear that,

I think it could be customizable enough by doing 2 things:

1. Have a setting with the compiler the user can set, like a string with vscode variable support: `gcc ${currentFile} -o bin/out.exe`
1. A regular expression to parse the output. Sadly there is no group names in js, but maybe there could be a workaround like mapping the array indizes: { errorLevel: 1, message: 3, line: 2 }, etc.
1. Maybe make it selectable to use stdout or stderr, not sure if every compiler uses stderr

So it would be possible to provide some default settings, but also any compiler would be usable.

What do you think?

**Comment by matthewferreira** [comment]
Sorry for the long delay in responding. At least for number 3, probably best to capture both, as if you use regexes as in number 2, it would be safe to do so. For number 1, is the idea to invoke the compiler? Probably a user has their own parameters and config setup, and would not want to duplicate that into an extension. Trying to parse makefiles or project files for compiler options is obviously well beyond the scope of this extension. Otherwise I was poking through your CppDiagnosticProvider, which I think is the most obvious addition to do right away, and easy since you did it :)

**Comment by agauniyal** [comment]
I think keeping compiler output/errors out of this plugin would be better since it's users installed it only for cppcheck. But having cppcheck output inside the code would be very good for us 👍 .

**Comment by matthewferreira** [comment]
I agree. I am planning to release a new version that includes linting functionality in the Problems view and as underlines in the code. It is derived from apazureck's fork, but expanded to run on the entire workspace instead of single files.
