### ISSUE TITLE
Making cppcheck-extension work out-of-the-box?

### ISSUE THREAD

**Issue by bitjson** [matthewferreira/cppcheck-extension#3]
Thanks for the fantastic extension! It took me a little digging around to figure out how to get started – is there any reason why the following settings aren't enabled by default?

```json
    "cppcheck.enable": true,
    "cppcheck.lintingEnabled": true
```

**Comment by matthewferreira** [comment]
For 'cppcheck.enable' I have no excuse. For linting, the idea is to enable it on a per-workspace basis. I did not think it best to assume the user would want a feature that is potentially intensive. I suppose a little documentation would have gone a long way.

**Comment by matthewferreira** [comment]
Your changes have been merged in and released, thank you. In addition, 'cppcheck.enabled' is now true out of the box.

**Comment by bitjson** [comment]
Thanks for the quick response! I can confirm both changes are working perfectly for me on macOS, thanks!
