### ISSUE TITLE
Does not allow to use variables?

### ISSUE THREAD

**Issue by zgoda** [matthewferreira/cppcheck-extension#5]
My paths are configured as follows:

```json
  "cppcheck.includePaths": [
    "${ESP_HOME}/xtensa-lx106-elf/xtensa-lx106-elf/include",
    "${SMING_HOME}",
    "${SMING_HOME}/system/include",
    "${workspaceRoot}/lib",
    "${workspaceRoot}/include"
  ]
```

But I keep getting:

```
(information) Couldn't find path given by -I '${ESP_HOME}/xtensa-lx106-elf/xtensa-lx106-elf/include/'
(information) Couldn't find path given by -I '${SMING_HOME}/'
(information) Couldn't find path given by -I '${SMING_HOME}/system/include/'
(information) Couldn't find path given by -I '${workspaceRoot}/lib/'
(information) Couldn't find path given by -I '${workspaceRoot}/include/'
```

It would be nice to have variables expanded by extension (both envvars like `ESP_HOME` and VS Code variables like `workspaceRoot`) before calling `cppcheck`. Moreover, these paths are configured exactly as for [C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) and now require copying from one place to another.

**Comment by matthewferreira** [comment]
This is doable. vscode has a several built-in variables (https://code.visualstudio.com/docs/editor/tasks#_variable-substitution), but I think the only useful one is ${workspaceRoot}.

**Comment by matthewferreira** [comment]
Does version 0.0.8 resolve this for you?

**Comment by zgoda** [comment]
Yes, thank you.
