### ISSUE TITLE
Linting errors not visible in problems view or editor windows

### ISSUE THREAD

**Issue by rjoomen** [matthewferreira/cppcheck-extension#7]
CppCheck does not show errors in problems view, nor in the editor. It also does not lint automatically. I did set:
`"cppcheck.enable": true,
"cppcheck.lintingEnabled": true`

Running via the command pane works, but again without reporting in problems view, only in the console output.

Could you give some pointers on how to fix or debug this?

Versions:
vscode-cppcheck 0.0.7
cppcheck 1.77
VSCode 1.12.1
Fedora 25

Edit: Same on Windows 10 with cppcheck 1.78

**Comment by matthewferreira** [comment]
Do you have 'cppcheck.verbose' set to true?

**Comment by rjoomen** [comment]
Hey, no verbose is not the problem. But I noticed you fixed that anyway. 
I'll try some debugging myself, I'll keep you posted.

**Comment by matthewferreira** [comment]
With the new 'force' and 'inconclusive' options, are there any changes?

**Comment by jritts** [comment]
I'm seeing the same issues with (not) listing output in the Problems view, nor running automatically upon a save.  Running manually works.

**Comment by matthewferreira** [comment]
@rjoomen I undid your pull request because the regex you have is too greedy, and matches everything until the last line output by cppcheck. I have the corrected regex based on yours, but do you want to try fixing it again and creating another pull? If not I'll put the fix in on Tuesday.

**Comment by rjoomen** [comment]
Sorry for the wrong pull request: I tested it with only one linting error, in which case it actually works. 
I fixed it, and tested it with multiple errors this time.
