### ISSUE TITLE
--language support

### ISSUE THREAD

**Issue by kamejosh** [matthewferreira/cppcheck-extension#9]
would it be possible to also add the --language option? 
I work with a language that uses c++ syntax but the files don't end on cpp so cppcheck thinks they are c files and even though i specified --std with just c++11 it still tries to check with c syntax settings (e.g. doesn't recognize class keyword). 
calling the same command with --language=c++ works fine and provides the correct output.

**Comment by matthewferreira** [comment]
Added to version 0.1.1.

**Comment by kamejosh** [comment]
perfect, many thanks, you're awesome!
